### ISSUE TITLE
Icon Color

### ISSUE THREAD

**Issue by agusdoka** [aligorithm/easy_loader#1]
Hi! I don't know if I'm doing something wrong, but the property 'iconColor' doesn't work for me. The others properties works like a charm, but the color of the icon is always black, even when I give it a differente value in the constructor. This is my code:

EasyLoader(
            animation: Tween<Offset>(
              begin: Offset.zero,
              end: Offset.zero,
            ).animate(
              AnimationController(
                vsync: this,
              ),
            ),
            iconSize: 50,
            image: AssetImage("assets/images/logo.png"),
            iconColor: Colors.white,
          ),

After insepcting your code, I think that it is because the property is not used, like if the following line of code were missing:

color: widget.iconColor

Thank you!

**Comment by aligorithm** [comment]
Thanks for the catch! Will push an update soon. I'm also upgrading to sound null-safety

**Comment by aligorithm** [comment]
This has been fixed in 2.0.0
Please update and try again 👍🏾

**Comment by agusdoka** [comment]
Thank you for fixing it as quick!
